### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by javid-p84** [akottr/dragtable#4]
doen't work properly on RTL tables

**Comment by matfish2** [comment]
Go to `dragtable.css` line 13 

```css
.dragtable-sortable li {
    margin: 0; padding: 0; float: left; font-size: 1em; background: white; 
}
```

Change `float: left` to `float: right`
