### ISSUE TITLE
Tables that already have a margin are distorted.

### ISSUE THREAD

**Issue by brennancheung** [akottr/dragtable#40]
Steps to reproduce:
1) create a table
2) set margin-top: 50px
3) make the table draggable

Result:
The grey area is larger than the table.

Expected result:
The grey area should be the same size as the table.

**Comment by Mottie** [comment]
If you add the following to the `dragtable.css` file, it'll fix the problem:

```css
.dragtable-sortable table {
	margin-top: 0;
}
```
